spring:
  datasource:
    url: jdbc:mysql://nextgenorientationets.mysql.database.azure.com:3306/storingorientation?useSSL=true&requireSSL=true
    username: nextgen
    password: Devz2025!

  jpa:
    hibernate:
      ddl-auto: create # can be switched to "update"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  level:
    org:
      springframework: DEBUG