spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storingorientation?useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create # can be switched to "update"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  level:
    org:
      springframework: DEBUG